name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### Please fill out the following information. Include as much detail as possible to help us understand the issue. Screen captures are very helpful."

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (name and version)
      placeholder: e.g. Google Chrome 116.0.5845.96
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click '...'
        3. See error
        
        If applicable, include (or link) any specific data (ie file analysed or exported project json) used.
        If you expected an outcome but got something else, please describe both (expected and actual) too.

    validations:
      required: true
